const authForm=document.getElementById('authForm'),authMsg=document.getElementById('msg'),authBtn=document.getElementById('authSubmit'),modeBtn=document.getElementById('authMode');
const next=new URLSearchParams(location.search).get('next')==='/estimate'?'/estimate':'/estimate';let mode='signup';
function setMode(value){mode=value;document.getElementById('authTitle').textContent=mode==='signup'?'Create your free account':'Sign in to your account';document.getElementById('businessLabel').hidden=mode==='login';document.getElementById('password').minLength=mode==='signup'?8:1;document.getElementById('password').autocomplete=mode==='signup'?'new-password':'current-password';authBtn.textContent=mode==='signup'?'Create account and continue':'Sign in and continue';modeBtn.textContent=mode==='signup'?'Already have an account? Sign in':'New here? Create a free account';authMsg.textContent='';}
modeBtn.onclick=()=>setMode(mode==='signup'?'login':'signup');
if(new URLSearchParams(location.search).get('mode')==='login')setMode('login');
if(next==='/estimate'){document.getElementById('authNote').textContent='Free estimates. No card. After signing in, return to your estimate without losing your draft.';try{const draft=JSON.parse(sessionStorage.getItem('cs_estimate_draft_v1')||'null');if(draft?.data?.business)document.getElementById('abusiness').value=draft.data.business}catch{}}
authForm.onsubmit=async ev=>{ev.preventDefault();authBtn.disabled=true;authMsg.textContent=mode==='signup'?'Creating account...':'Signing in...';try{const response=await fetch('/api/'+mode,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({business:document.getElementById('abusiness').value.trim(),email:document.getElementById('email').value.trim(),password:document.getElementById('password').value})});const result=await response.json();if(!response.ok){authMsg.textContent=response.status===409?'This email already has an account. Use Sign in below.':result.error||'Could not continue. Try again.';return}location.assign(next)}catch{authMsg.textContent='Connection problem. Your draft is still here. Try again.'}finally{authBtn.disabled=false}};
async function loadAccount(){try{const r=await fetch('/api/me');if(!r.ok)return;const d=await r.json();document.getElementById('authSection').hidden=true;document.getElementById('signedSection').hidden=false;document.getElementById('accountEmail').textContent=d.email;document.getElementById('continueLink').href=next==='/estimate'?next:'/estimate';document.getElementById('paymentSection').hidden=false;document.getElementById('paymentUrl').value=d.paymentUrl||''}catch{authMsg.textContent='Could not check your account. Try signing in.'}}
document.getElementById('savePayment').onclick=async()=>{let msg=document.getElementById('paymentMessage'),button=document.getElementById('savePayment');button.disabled=true;try{const r=await fetch('/api/account/payment-link',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({paymentUrl:document.getElementById('paymentUrl').value.trim()})}),d=await r.json();msg.textContent=r.ok?'Saved for future invoices. Existing invoices keep their own link.':d.error||'Could not save'}catch{msg.textContent='Connection problem. Try again.'}finally{button.disabled=false}};
loadAccount();
